version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ${DOCKERFILE:-Dockerfile.cpu}
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-}
   
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
