main:
  name: 'object_detection'
  seed: 24
  cuda: True

data_loader:
  type: 'CustomDataLoader'
  args: # see utils/data_loader.py
    data_dir: 'data/'
    batch_size: 32
    shuffle: True
    validation_split: 0.1
    num_workers: 8

arch:
  type: 'Yolov9c'
  args: {} # see model/model.py
optimizer:
  type: 'Adam'
  args: # see torch.optim
    lr: 5.e-4
lr_scheduler:
  type: 'ExponentialLR'
  args: # see torch.optim.lr_scheduler
    gamma: 0.98

loss:
  type: 'CrossEntropyLoss'
  args: # see model/losses.py
    multiplier: 1
metrics: # see model/metrics.py
  - 'accuracy'

trainer:
  epochs: 100  # 100 in paper
  log_step: 1700  # log data every x step
  save_dir: 'data/runs/'
  save_period: 5  # save model every x epoch
  verbosity: 0  # see main.verbosity
  monitor: 'min val_loss'  # '{min|max} {metrics}'
  early_stop: 10  # stop after x epoch not improving