# Generated by Django 5.0.6 on 2024-05-31 00:41

import profiles.models
import profiles.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_photo_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                storage=profiles.storage.ProtectedMediaStorage,
                upload_to=profiles.models.user_directory_path,
            ),
        ),
    ]
