# Generated by Django 5.0.6 on 2024-06-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_dataset_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="istrain",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(default="PENDING", max_length=50),
        ),
    ]
