# Generated by Django 5.0.6 on 2024-06-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_task_istrain_alter_task_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="istrain",
            new_name="is_train",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
