# Generated by Django 5.0.6 on 2024-06-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0015_remove_task_is_train_training"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="keywords",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
