# Generated by Django 5.0.6 on 2024-06-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_remove_training_task_id_training_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="epochs",
            field=models.IntegerField(default=0),
        ),
    ]
