# Generated by Django 5.0.6 on 2024-06-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0018_training_epochs"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
